server:
  addr: ":53"

zones:
  - origin: godns.co.za.
    ttl: 300
    records:
      "@":
        soa:
          ns: ns1.godns.co.za.
          mbox: hostmaster.godns.co.za.
          serial: 2026052301
        ns:
          - ns1.godns.co.za.
          - ns2.godns.co.za.
      ns1:
        a:
          - 46.101.233.116
      ns2:
        a:
          - 165.22.73.121

  # - origin: barenderasmus.com.
  #   ttl: 300
  #   records:
  #     "@":
  #       soa:
  #         ns: ns1.godns.co.za.
  #         mbox: hostmaster.barenderasmus.com.
  #         serial: 2026052201
  #       ns:
  #         - ns1.godns.co.za.
  #         - ns2.godns.co.za.
  #       cname: barenderasmus-com.web.app.
  #       a:
  #         - 192.0.2.100
